export const dummyDeliveryRecruitment = [
  {
    id: 1,
    userId: 1,
    restaurant: '여우골 서교점',
    menu: '연어 세트',
    timer: 2,
    recruited: 3,
    recruit: 4,
    cost: 12800,
    recruiter: '마이멜로디',
    foodtype: 'japanese',
    location: '한우리집',
    participants: ['폼폼푸린', '토니토니쵸파'],
    postBody: '함께 드실 분',
    account: 123456,
    status: [1, 2],
    isValid: 3,
  },
  {
    id: 2,
    userId: 2,
    restaurant: 'BBQ 신촌점',
    menu: '황금올리브치킨',
    timer: 5,
    recruited: 2,
    recruit: 3,
    cost: 8500,
    recruiter: '이화',
    foodtype: 'franchise',
    building: '이하우스',
    participants: [],
    content: '함께 드실 분',
    account: 123456,
    status: [],
    isValid: 1,
  },
];
